// Code generated by internal/generated/opendartapi/generate_split.py; DO NOT EDIT.

package opendart

import opendartschema "github.com/awuzag/opendart/internal/generated/opendartschema"

// ListItem is a generated OpenDART API schema type.
type ListItem = opendartschema.ListItem

// ListResponse is a generated OpenDART API schema type.
type ListResponse = opendartschema.ListResponse

// ListParams is a generated OpenDART API schema type.
type ListParams = opendartschema.ListParams

// CompanyResponse is a generated OpenDART API schema type.
type CompanyResponse = opendartschema.CompanyResponse

// CompanyParams is a generated OpenDART API schema type.
type CompanyParams = opendartschema.CompanyParams

// DocumentParams is a generated OpenDART API schema type.
type DocumentParams = opendartschema.DocumentParams

// IrdsSttusItem is a generated OpenDART API schema type.
type IrdsSttusItem = opendartschema.IrdsSttusItem

// IrdsSttusResponse is a generated OpenDART API schema type.
type IrdsSttusResponse = opendartschema.IrdsSttusResponse

// IrdsSttusParams is a generated OpenDART API schema type.
type IrdsSttusParams = opendartschema.IrdsSttusParams

// AlotMatterItem is a generated OpenDART API schema type.
type AlotMatterItem = opendartschema.AlotMatterItem

// AlotMatterResponse is a generated OpenDART API schema type.
type AlotMatterResponse = opendartschema.AlotMatterResponse

// AlotMatterParams is a generated OpenDART API schema type.
type AlotMatterParams = opendartschema.AlotMatterParams

// TesstkAcqsDspsSttusItem is a generated OpenDART API schema type.
type TesstkAcqsDspsSttusItem = opendartschema.TesstkAcqsDspsSttusItem

// TesstkAcqsDspsSttusResponse is a generated OpenDART API schema type.
type TesstkAcqsDspsSttusResponse = opendartschema.TesstkAcqsDspsSttusResponse

// TesstkAcqsDspsSttusParams is a generated OpenDART API schema type.
type TesstkAcqsDspsSttusParams = opendartschema.TesstkAcqsDspsSttusParams

// HyslrSttusItem is a generated OpenDART API schema type.
type HyslrSttusItem = opendartschema.HyslrSttusItem

// HyslrSttusResponse is a generated OpenDART API schema type.
type HyslrSttusResponse = opendartschema.HyslrSttusResponse

// HyslrSttusParams is a generated OpenDART API schema type.
type HyslrSttusParams = opendartschema.HyslrSttusParams

// HyslrChgSttusItem is a generated OpenDART API schema type.
type HyslrChgSttusItem = opendartschema.HyslrChgSttusItem

// HyslrChgSttusResponse is a generated OpenDART API schema type.
type HyslrChgSttusResponse = opendartschema.HyslrChgSttusResponse

// HyslrChgSttusParams is a generated OpenDART API schema type.
type HyslrChgSttusParams = opendartschema.HyslrChgSttusParams

// MrhlSttusItem is a generated OpenDART API schema type.
type MrhlSttusItem = opendartschema.MrhlSttusItem

// MrhlSttusResponse is a generated OpenDART API schema type.
type MrhlSttusResponse = opendartschema.MrhlSttusResponse

// MrhlSttusParams is a generated OpenDART API schema type.
type MrhlSttusParams = opendartschema.MrhlSttusParams

// ExctvSttusItem is a generated OpenDART API schema type.
type ExctvSttusItem = opendartschema.ExctvSttusItem

// ExctvSttusResponse is a generated OpenDART API schema type.
type ExctvSttusResponse = opendartschema.ExctvSttusResponse

// ExctvSttusParams is a generated OpenDART API schema type.
type ExctvSttusParams = opendartschema.ExctvSttusParams

// EmpSttusItem is a generated OpenDART API schema type.
type EmpSttusItem = opendartschema.EmpSttusItem

// EmpSttusResponse is a generated OpenDART API schema type.
type EmpSttusResponse = opendartschema.EmpSttusResponse

// EmpSttusParams is a generated OpenDART API schema type.
type EmpSttusParams = opendartschema.EmpSttusParams

// HmvAuditIndvdlBySttusItem is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusItem = opendartschema.HmvAuditIndvdlBySttusItem

// HmvAuditIndvdlBySttusResponse is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusResponse = opendartschema.HmvAuditIndvdlBySttusResponse

// HmvAuditIndvdlBySttusParams is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusParams = opendartschema.HmvAuditIndvdlBySttusParams

// HmvAuditAllSttusItem is a generated OpenDART API schema type.
type HmvAuditAllSttusItem = opendartschema.HmvAuditAllSttusItem

// HmvAuditAllSttusResponse is a generated OpenDART API schema type.
type HmvAuditAllSttusResponse = opendartschema.HmvAuditAllSttusResponse

// HmvAuditAllSttusParams is a generated OpenDART API schema type.
type HmvAuditAllSttusParams = opendartschema.HmvAuditAllSttusParams

// IndvdlByPayItem is a generated OpenDART API schema type.
type IndvdlByPayItem = opendartschema.IndvdlByPayItem

// IndvdlByPayResponse is a generated OpenDART API schema type.
type IndvdlByPayResponse = opendartschema.IndvdlByPayResponse

// IndvdlByPayParams is a generated OpenDART API schema type.
type IndvdlByPayParams = opendartschema.IndvdlByPayParams

// OtrCprInvstmntSttusItem is a generated OpenDART API schema type.
type OtrCprInvstmntSttusItem = opendartschema.OtrCprInvstmntSttusItem

// OtrCprInvstmntSttusResponse is a generated OpenDART API schema type.
type OtrCprInvstmntSttusResponse = opendartschema.OtrCprInvstmntSttusResponse

// OtrCprInvstmntSttusParams is a generated OpenDART API schema type.
type OtrCprInvstmntSttusParams = opendartschema.OtrCprInvstmntSttusParams

// FnlttSinglAcntItem is a generated OpenDART API schema type.
type FnlttSinglAcntItem = opendartschema.FnlttSinglAcntItem

// FnlttSinglAcntResponse is a generated OpenDART API schema type.
type FnlttSinglAcntResponse = opendartschema.FnlttSinglAcntResponse

// FnlttSinglAcntParams is a generated OpenDART API schema type.
type FnlttSinglAcntParams = opendartschema.FnlttSinglAcntParams

// FnlttMultiAcntItem is a generated OpenDART API schema type.
type FnlttMultiAcntItem = opendartschema.FnlttMultiAcntItem

// FnlttMultiAcntResponse is a generated OpenDART API schema type.
type FnlttMultiAcntResponse = opendartschema.FnlttMultiAcntResponse

// FnlttMultiAcntParams is a generated OpenDART API schema type.
type FnlttMultiAcntParams = opendartschema.FnlttMultiAcntParams

// FnlttXbrlParams is a generated OpenDART API schema type.
type FnlttXbrlParams = opendartschema.FnlttXbrlParams

// FnlttSinglAcntAllItem is a generated OpenDART API schema type.
type FnlttSinglAcntAllItem = opendartschema.FnlttSinglAcntAllItem

// FnlttSinglAcntAllResponse is a generated OpenDART API schema type.
type FnlttSinglAcntAllResponse = opendartschema.FnlttSinglAcntAllResponse

// FnlttSinglAcntAllParams is a generated OpenDART API schema type.
type FnlttSinglAcntAllParams = opendartschema.FnlttSinglAcntAllParams

// MajorstockItem is a generated OpenDART API schema type.
type MajorstockItem = opendartschema.MajorstockItem

// MajorstockResponse is a generated OpenDART API schema type.
type MajorstockResponse = opendartschema.MajorstockResponse

// MajorstockParams is a generated OpenDART API schema type.
type MajorstockParams = opendartschema.MajorstockParams

// ElestockItem is a generated OpenDART API schema type.
type ElestockItem = opendartschema.ElestockItem

// ElestockResponse is a generated OpenDART API schema type.
type ElestockResponse = opendartschema.ElestockResponse

// ElestockParams is a generated OpenDART API schema type.
type ElestockParams = opendartschema.ElestockParams

// XbrlTaxonomyItem is a generated OpenDART API schema type.
type XbrlTaxonomyItem = opendartschema.XbrlTaxonomyItem

// XbrlTaxonomyResponse is a generated OpenDART API schema type.
type XbrlTaxonomyResponse = opendartschema.XbrlTaxonomyResponse

// XbrlTaxonomyParams is a generated OpenDART API schema type.
type XbrlTaxonomyParams = opendartschema.XbrlTaxonomyParams

// StockTotqySttusItem is a generated OpenDART API schema type.
type StockTotqySttusItem = opendartschema.StockTotqySttusItem

// StockTotqySttusResponse is a generated OpenDART API schema type.
type StockTotqySttusResponse = opendartschema.StockTotqySttusResponse

// StockTotqySttusParams is a generated OpenDART API schema type.
type StockTotqySttusParams = opendartschema.StockTotqySttusParams

// DetScritsIsuAcmsltItem is a generated OpenDART API schema type.
type DetScritsIsuAcmsltItem = opendartschema.DetScritsIsuAcmsltItem

// DetScritsIsuAcmsltResponse is a generated OpenDART API schema type.
type DetScritsIsuAcmsltResponse = opendartschema.DetScritsIsuAcmsltResponse

// DetScritsIsuAcmsltParams is a generated OpenDART API schema type.
type DetScritsIsuAcmsltParams = opendartschema.DetScritsIsuAcmsltParams

// EntrprsBilScritsNrdmpBlceItem is a generated OpenDART API schema type.
type EntrprsBilScritsNrdmpBlceItem = opendartschema.EntrprsBilScritsNrdmpBlceItem

// EntrprsBilScritsNrdmpBlceResponse is a generated OpenDART API schema type.
type EntrprsBilScritsNrdmpBlceResponse = opendartschema.EntrprsBilScritsNrdmpBlceResponse

// EntrprsBilScritsNrdmpBlceParams is a generated OpenDART API schema type.
type EntrprsBilScritsNrdmpBlceParams = opendartschema.EntrprsBilScritsNrdmpBlceParams

// SrtpdPsndbtNrdmpBlceItem is a generated OpenDART API schema type.
type SrtpdPsndbtNrdmpBlceItem = opendartschema.SrtpdPsndbtNrdmpBlceItem

// SrtpdPsndbtNrdmpBlceResponse is a generated OpenDART API schema type.
type SrtpdPsndbtNrdmpBlceResponse = opendartschema.SrtpdPsndbtNrdmpBlceResponse

// SrtpdPsndbtNrdmpBlceParams is a generated OpenDART API schema type.
type SrtpdPsndbtNrdmpBlceParams = opendartschema.SrtpdPsndbtNrdmpBlceParams

// CprndNrdmpBlceItem is a generated OpenDART API schema type.
type CprndNrdmpBlceItem = opendartschema.CprndNrdmpBlceItem

// CprndNrdmpBlceResponse is a generated OpenDART API schema type.
type CprndNrdmpBlceResponse = opendartschema.CprndNrdmpBlceResponse

// CprndNrdmpBlceParams is a generated OpenDART API schema type.
type CprndNrdmpBlceParams = opendartschema.CprndNrdmpBlceParams

// NewCaplScritsNrdmpBlceItem is a generated OpenDART API schema type.
type NewCaplScritsNrdmpBlceItem = opendartschema.NewCaplScritsNrdmpBlceItem

// NewCaplScritsNrdmpBlceResponse is a generated OpenDART API schema type.
type NewCaplScritsNrdmpBlceResponse = opendartschema.NewCaplScritsNrdmpBlceResponse

// NewCaplScritsNrdmpBlceParams is a generated OpenDART API schema type.
type NewCaplScritsNrdmpBlceParams = opendartschema.NewCaplScritsNrdmpBlceParams

// CndlCaplScritsNrdmpBlceItem is a generated OpenDART API schema type.
type CndlCaplScritsNrdmpBlceItem = opendartschema.CndlCaplScritsNrdmpBlceItem

// CndlCaplScritsNrdmpBlceResponse is a generated OpenDART API schema type.
type CndlCaplScritsNrdmpBlceResponse = opendartschema.CndlCaplScritsNrdmpBlceResponse

// CndlCaplScritsNrdmpBlceParams is a generated OpenDART API schema type.
type CndlCaplScritsNrdmpBlceParams = opendartschema.CndlCaplScritsNrdmpBlceParams

// AccnutAdtorNmNdAdtOpinionItem is a generated OpenDART API schema type.
type AccnutAdtorNmNdAdtOpinionItem = opendartschema.AccnutAdtorNmNdAdtOpinionItem

// AccnutAdtorNmNdAdtOpinionResponse is a generated OpenDART API schema type.
type AccnutAdtorNmNdAdtOpinionResponse = opendartschema.AccnutAdtorNmNdAdtOpinionResponse

// AccnutAdtorNmNdAdtOpinionParams is a generated OpenDART API schema type.
type AccnutAdtorNmNdAdtOpinionParams = opendartschema.AccnutAdtorNmNdAdtOpinionParams

// AdtServcCnclsSttusItem is a generated OpenDART API schema type.
type AdtServcCnclsSttusItem = opendartschema.AdtServcCnclsSttusItem

// AdtServcCnclsSttusResponse is a generated OpenDART API schema type.
type AdtServcCnclsSttusResponse = opendartschema.AdtServcCnclsSttusResponse

// AdtServcCnclsSttusParams is a generated OpenDART API schema type.
type AdtServcCnclsSttusParams = opendartschema.AdtServcCnclsSttusParams

// AccnutAdtorNonAdtServcCnclsSttusItem is a generated OpenDART API schema type.
type AccnutAdtorNonAdtServcCnclsSttusItem = opendartschema.AccnutAdtorNonAdtServcCnclsSttusItem

// AccnutAdtorNonAdtServcCnclsSttusResponse is a generated OpenDART API schema type.
type AccnutAdtorNonAdtServcCnclsSttusResponse = opendartschema.AccnutAdtorNonAdtServcCnclsSttusResponse

// AccnutAdtorNonAdtServcCnclsSttusParams is a generated OpenDART API schema type.
type AccnutAdtorNonAdtServcCnclsSttusParams = opendartschema.AccnutAdtorNonAdtServcCnclsSttusParams

// OutcmpnyDrctrNdChangeSttusItem is a generated OpenDART API schema type.
type OutcmpnyDrctrNdChangeSttusItem = opendartschema.OutcmpnyDrctrNdChangeSttusItem

// OutcmpnyDrctrNdChangeSttusResponse is a generated OpenDART API schema type.
type OutcmpnyDrctrNdChangeSttusResponse = opendartschema.OutcmpnyDrctrNdChangeSttusResponse

// OutcmpnyDrctrNdChangeSttusParams is a generated OpenDART API schema type.
type OutcmpnyDrctrNdChangeSttusParams = opendartschema.OutcmpnyDrctrNdChangeSttusParams

// UnrstExctvMendngSttusItem is a generated OpenDART API schema type.
type UnrstExctvMendngSttusItem = opendartschema.UnrstExctvMendngSttusItem

// UnrstExctvMendngSttusResponse is a generated OpenDART API schema type.
type UnrstExctvMendngSttusResponse = opendartschema.UnrstExctvMendngSttusResponse

// UnrstExctvMendngSttusParams is a generated OpenDART API schema type.
type UnrstExctvMendngSttusParams = opendartschema.UnrstExctvMendngSttusParams

// DrctrAdtAllMendngSttusGmtsckConfmAmountItem is a generated OpenDART API schema type.
type DrctrAdtAllMendngSttusGmtsckConfmAmountItem = opendartschema.DrctrAdtAllMendngSttusGmtsckConfmAmountItem

// DrctrAdtAllMendngSttusGmtsckConfmAmountResponse is a generated OpenDART API schema type.
type DrctrAdtAllMendngSttusGmtsckConfmAmountResponse = opendartschema.DrctrAdtAllMendngSttusGmtsckConfmAmountResponse

// DrctrAdtAllMendngSttusGmtsckConfmAmountParams is a generated OpenDART API schema type.
type DrctrAdtAllMendngSttusGmtsckConfmAmountParams = opendartschema.DrctrAdtAllMendngSttusGmtsckConfmAmountParams

// DrctrAdtAllMendngSttusMendngPymntamtTyClItem is a generated OpenDART API schema type.
type DrctrAdtAllMendngSttusMendngPymntamtTyClItem = opendartschema.DrctrAdtAllMendngSttusMendngPymntamtTyClItem

// DrctrAdtAllMendngSttusMendngPymntamtTyClResponse is a generated OpenDART API schema type.
type DrctrAdtAllMendngSttusMendngPymntamtTyClResponse = opendartschema.DrctrAdtAllMendngSttusMendngPymntamtTyClResponse

// DrctrAdtAllMendngSttusMendngPymntamtTyClParams is a generated OpenDART API schema type.
type DrctrAdtAllMendngSttusMendngPymntamtTyClParams = opendartschema.DrctrAdtAllMendngSttusMendngPymntamtTyClParams

// PssrpCptalUseDtlsItem is a generated OpenDART API schema type.
type PssrpCptalUseDtlsItem = opendartschema.PssrpCptalUseDtlsItem

// PssrpCptalUseDtlsResponse is a generated OpenDART API schema type.
type PssrpCptalUseDtlsResponse = opendartschema.PssrpCptalUseDtlsResponse

// PssrpCptalUseDtlsParams is a generated OpenDART API schema type.
type PssrpCptalUseDtlsParams = opendartschema.PssrpCptalUseDtlsParams

// PrvsrpCptalUseDtlsItem is a generated OpenDART API schema type.
type PrvsrpCptalUseDtlsItem = opendartschema.PrvsrpCptalUseDtlsItem

// PrvsrpCptalUseDtlsResponse is a generated OpenDART API schema type.
type PrvsrpCptalUseDtlsResponse = opendartschema.PrvsrpCptalUseDtlsResponse

// PrvsrpCptalUseDtlsParams is a generated OpenDART API schema type.
type PrvsrpCptalUseDtlsParams = opendartschema.PrvsrpCptalUseDtlsParams

// AstInhtrfEtcPtbkOptItem is a generated OpenDART API schema type.
type AstInhtrfEtcPtbkOptItem = opendartschema.AstInhtrfEtcPtbkOptItem

// AstInhtrfEtcPtbkOptResponse is a generated OpenDART API schema type.
type AstInhtrfEtcPtbkOptResponse = opendartschema.AstInhtrfEtcPtbkOptResponse

// AstInhtrfEtcPtbkOptParams is a generated OpenDART API schema type.
type AstInhtrfEtcPtbkOptParams = opendartschema.AstInhtrfEtcPtbkOptParams

// DfOcrItem is a generated OpenDART API schema type.
type DfOcrItem = opendartschema.DfOcrItem

// DfOcrResponse is a generated OpenDART API schema type.
type DfOcrResponse = opendartschema.DfOcrResponse

// DfOcrParams is a generated OpenDART API schema type.
type DfOcrParams = opendartschema.DfOcrParams

// BsnSpItem is a generated OpenDART API schema type.
type BsnSpItem = opendartschema.BsnSpItem

// BsnSpResponse is a generated OpenDART API schema type.
type BsnSpResponse = opendartschema.BsnSpResponse

// BsnSpParams is a generated OpenDART API schema type.
type BsnSpParams = opendartschema.BsnSpParams

// CtrcvsBgrqItem is a generated OpenDART API schema type.
type CtrcvsBgrqItem = opendartschema.CtrcvsBgrqItem

// CtrcvsBgrqResponse is a generated OpenDART API schema type.
type CtrcvsBgrqResponse = opendartschema.CtrcvsBgrqResponse

// CtrcvsBgrqParams is a generated OpenDART API schema type.
type CtrcvsBgrqParams = opendartschema.CtrcvsBgrqParams

// DsRsOcrItem is a generated OpenDART API schema type.
type DsRsOcrItem = opendartschema.DsRsOcrItem

// DsRsOcrResponse is a generated OpenDART API schema type.
type DsRsOcrResponse = opendartschema.DsRsOcrResponse

// DsRsOcrParams is a generated OpenDART API schema type.
type DsRsOcrParams = opendartschema.DsRsOcrParams

// PiicDecsnItem is a generated OpenDART API schema type.
type PiicDecsnItem = opendartschema.PiicDecsnItem

// PiicDecsnResponse is a generated OpenDART API schema type.
type PiicDecsnResponse = opendartschema.PiicDecsnResponse

// PiicDecsnParams is a generated OpenDART API schema type.
type PiicDecsnParams = opendartschema.PiicDecsnParams

// FricDecsnItem is a generated OpenDART API schema type.
type FricDecsnItem = opendartschema.FricDecsnItem

// FricDecsnResponse is a generated OpenDART API schema type.
type FricDecsnResponse = opendartschema.FricDecsnResponse

// FricDecsnParams is a generated OpenDART API schema type.
type FricDecsnParams = opendartschema.FricDecsnParams

// PifricDecsnItem is a generated OpenDART API schema type.
type PifricDecsnItem = opendartschema.PifricDecsnItem

// PifricDecsnResponse is a generated OpenDART API schema type.
type PifricDecsnResponse = opendartschema.PifricDecsnResponse

// PifricDecsnParams is a generated OpenDART API schema type.
type PifricDecsnParams = opendartschema.PifricDecsnParams

// CrDecsnItem is a generated OpenDART API schema type.
type CrDecsnItem = opendartschema.CrDecsnItem

// CrDecsnResponse is a generated OpenDART API schema type.
type CrDecsnResponse = opendartschema.CrDecsnResponse

// CrDecsnParams is a generated OpenDART API schema type.
type CrDecsnParams = opendartschema.CrDecsnParams

// BnkMngtPcbgItem is a generated OpenDART API schema type.
type BnkMngtPcbgItem = opendartschema.BnkMngtPcbgItem

// BnkMngtPcbgResponse is a generated OpenDART API schema type.
type BnkMngtPcbgResponse = opendartschema.BnkMngtPcbgResponse

// BnkMngtPcbgParams is a generated OpenDART API schema type.
type BnkMngtPcbgParams = opendartschema.BnkMngtPcbgParams

// LwstLgItem is a generated OpenDART API schema type.
type LwstLgItem = opendartschema.LwstLgItem

// LwstLgResponse is a generated OpenDART API schema type.
type LwstLgResponse = opendartschema.LwstLgResponse

// LwstLgParams is a generated OpenDART API schema type.
type LwstLgParams = opendartschema.LwstLgParams

// OvLstDecsnItem is a generated OpenDART API schema type.
type OvLstDecsnItem = opendartschema.OvLstDecsnItem

// OvLstDecsnResponse is a generated OpenDART API schema type.
type OvLstDecsnResponse = opendartschema.OvLstDecsnResponse

// OvLstDecsnParams is a generated OpenDART API schema type.
type OvLstDecsnParams = opendartschema.OvLstDecsnParams

// OvDlstDecsnItem is a generated OpenDART API schema type.
type OvDlstDecsnItem = opendartschema.OvDlstDecsnItem

// OvDlstDecsnResponse is a generated OpenDART API schema type.
type OvDlstDecsnResponse = opendartschema.OvDlstDecsnResponse

// OvDlstDecsnParams is a generated OpenDART API schema type.
type OvDlstDecsnParams = opendartschema.OvDlstDecsnParams

// OvLstItem is a generated OpenDART API schema type.
type OvLstItem = opendartschema.OvLstItem

// OvLstResponse is a generated OpenDART API schema type.
type OvLstResponse = opendartschema.OvLstResponse

// OvLstParams is a generated OpenDART API schema type.
type OvLstParams = opendartschema.OvLstParams

// OvDlstItem is a generated OpenDART API schema type.
type OvDlstItem = opendartschema.OvDlstItem

// OvDlstResponse is a generated OpenDART API schema type.
type OvDlstResponse = opendartschema.OvDlstResponse

// OvDlstParams is a generated OpenDART API schema type.
type OvDlstParams = opendartschema.OvDlstParams

// CvbdIsDecsnItem is a generated OpenDART API schema type.
type CvbdIsDecsnItem = opendartschema.CvbdIsDecsnItem

// CvbdIsDecsnResponse is a generated OpenDART API schema type.
type CvbdIsDecsnResponse = opendartschema.CvbdIsDecsnResponse

// CvbdIsDecsnParams is a generated OpenDART API schema type.
type CvbdIsDecsnParams = opendartschema.CvbdIsDecsnParams

// BdwtIsDecsnItem is a generated OpenDART API schema type.
type BdwtIsDecsnItem = opendartschema.BdwtIsDecsnItem

// BdwtIsDecsnResponse is a generated OpenDART API schema type.
type BdwtIsDecsnResponse = opendartschema.BdwtIsDecsnResponse

// BdwtIsDecsnParams is a generated OpenDART API schema type.
type BdwtIsDecsnParams = opendartschema.BdwtIsDecsnParams

// ExbdIsDecsnItem is a generated OpenDART API schema type.
type ExbdIsDecsnItem = opendartschema.ExbdIsDecsnItem

// ExbdIsDecsnResponse is a generated OpenDART API schema type.
type ExbdIsDecsnResponse = opendartschema.ExbdIsDecsnResponse

// ExbdIsDecsnParams is a generated OpenDART API schema type.
type ExbdIsDecsnParams = opendartschema.ExbdIsDecsnParams

// BnkMngtPcspItem is a generated OpenDART API schema type.
type BnkMngtPcspItem = opendartschema.BnkMngtPcspItem

// BnkMngtPcspResponse is a generated OpenDART API schema type.
type BnkMngtPcspResponse = opendartschema.BnkMngtPcspResponse

// BnkMngtPcspParams is a generated OpenDART API schema type.
type BnkMngtPcspParams = opendartschema.BnkMngtPcspParams

// WdCocobdIsDecsnItem is a generated OpenDART API schema type.
type WdCocobdIsDecsnItem = opendartschema.WdCocobdIsDecsnItem

// WdCocobdIsDecsnResponse is a generated OpenDART API schema type.
type WdCocobdIsDecsnResponse = opendartschema.WdCocobdIsDecsnResponse

// WdCocobdIsDecsnParams is a generated OpenDART API schema type.
type WdCocobdIsDecsnParams = opendartschema.WdCocobdIsDecsnParams

// TsstkAqDecsnItem is a generated OpenDART API schema type.
type TsstkAqDecsnItem = opendartschema.TsstkAqDecsnItem

// TsstkAqDecsnResponse is a generated OpenDART API schema type.
type TsstkAqDecsnResponse = opendartschema.TsstkAqDecsnResponse

// TsstkAqDecsnParams is a generated OpenDART API schema type.
type TsstkAqDecsnParams = opendartschema.TsstkAqDecsnParams

// TsstkDpDecsnItem is a generated OpenDART API schema type.
type TsstkDpDecsnItem = opendartschema.TsstkDpDecsnItem

// TsstkDpDecsnResponse is a generated OpenDART API schema type.
type TsstkDpDecsnResponse = opendartschema.TsstkDpDecsnResponse

// TsstkDpDecsnParams is a generated OpenDART API schema type.
type TsstkDpDecsnParams = opendartschema.TsstkDpDecsnParams

// TsstkAqTrctrCnsDecsnItem is a generated OpenDART API schema type.
type TsstkAqTrctrCnsDecsnItem = opendartschema.TsstkAqTrctrCnsDecsnItem

// TsstkAqTrctrCnsDecsnResponse is a generated OpenDART API schema type.
type TsstkAqTrctrCnsDecsnResponse = opendartschema.TsstkAqTrctrCnsDecsnResponse

// TsstkAqTrctrCnsDecsnParams is a generated OpenDART API schema type.
type TsstkAqTrctrCnsDecsnParams = opendartschema.TsstkAqTrctrCnsDecsnParams

// TsstkAqTrctrCcDecsnItem is a generated OpenDART API schema type.
type TsstkAqTrctrCcDecsnItem = opendartschema.TsstkAqTrctrCcDecsnItem

// TsstkAqTrctrCcDecsnResponse is a generated OpenDART API schema type.
type TsstkAqTrctrCcDecsnResponse = opendartschema.TsstkAqTrctrCcDecsnResponse

// TsstkAqTrctrCcDecsnParams is a generated OpenDART API schema type.
type TsstkAqTrctrCcDecsnParams = opendartschema.TsstkAqTrctrCcDecsnParams

// BsnInhDecsnItem is a generated OpenDART API schema type.
type BsnInhDecsnItem = opendartschema.BsnInhDecsnItem

// BsnInhDecsnResponse is a generated OpenDART API schema type.
type BsnInhDecsnResponse = opendartschema.BsnInhDecsnResponse

// BsnInhDecsnParams is a generated OpenDART API schema type.
type BsnInhDecsnParams = opendartschema.BsnInhDecsnParams

// BsnTrfDecsnItem is a generated OpenDART API schema type.
type BsnTrfDecsnItem = opendartschema.BsnTrfDecsnItem

// BsnTrfDecsnResponse is a generated OpenDART API schema type.
type BsnTrfDecsnResponse = opendartschema.BsnTrfDecsnResponse

// BsnTrfDecsnParams is a generated OpenDART API schema type.
type BsnTrfDecsnParams = opendartschema.BsnTrfDecsnParams

// TgastInhDecsnItem is a generated OpenDART API schema type.
type TgastInhDecsnItem = opendartschema.TgastInhDecsnItem

// TgastInhDecsnResponse is a generated OpenDART API schema type.
type TgastInhDecsnResponse = opendartschema.TgastInhDecsnResponse

// TgastInhDecsnParams is a generated OpenDART API schema type.
type TgastInhDecsnParams = opendartschema.TgastInhDecsnParams

// TgastTrfDecsnItem is a generated OpenDART API schema type.
type TgastTrfDecsnItem = opendartschema.TgastTrfDecsnItem

// TgastTrfDecsnResponse is a generated OpenDART API schema type.
type TgastTrfDecsnResponse = opendartschema.TgastTrfDecsnResponse

// TgastTrfDecsnParams is a generated OpenDART API schema type.
type TgastTrfDecsnParams = opendartschema.TgastTrfDecsnParams

// OtcprStkInvscrInhDecsnItem is a generated OpenDART API schema type.
type OtcprStkInvscrInhDecsnItem = opendartschema.OtcprStkInvscrInhDecsnItem

// OtcprStkInvscrInhDecsnResponse is a generated OpenDART API schema type.
type OtcprStkInvscrInhDecsnResponse = opendartschema.OtcprStkInvscrInhDecsnResponse

// OtcprStkInvscrInhDecsnParams is a generated OpenDART API schema type.
type OtcprStkInvscrInhDecsnParams = opendartschema.OtcprStkInvscrInhDecsnParams

// OtcprStkInvscrTrfDecsnItem is a generated OpenDART API schema type.
type OtcprStkInvscrTrfDecsnItem = opendartschema.OtcprStkInvscrTrfDecsnItem

// OtcprStkInvscrTrfDecsnResponse is a generated OpenDART API schema type.
type OtcprStkInvscrTrfDecsnResponse = opendartschema.OtcprStkInvscrTrfDecsnResponse

// OtcprStkInvscrTrfDecsnParams is a generated OpenDART API schema type.
type OtcprStkInvscrTrfDecsnParams = opendartschema.OtcprStkInvscrTrfDecsnParams

// StkrtbdInhDecsnItem is a generated OpenDART API schema type.
type StkrtbdInhDecsnItem = opendartschema.StkrtbdInhDecsnItem

// StkrtbdInhDecsnResponse is a generated OpenDART API schema type.
type StkrtbdInhDecsnResponse = opendartschema.StkrtbdInhDecsnResponse

// StkrtbdInhDecsnParams is a generated OpenDART API schema type.
type StkrtbdInhDecsnParams = opendartschema.StkrtbdInhDecsnParams

// StkrtbdTrfDecsnItem is a generated OpenDART API schema type.
type StkrtbdTrfDecsnItem = opendartschema.StkrtbdTrfDecsnItem

// StkrtbdTrfDecsnResponse is a generated OpenDART API schema type.
type StkrtbdTrfDecsnResponse = opendartschema.StkrtbdTrfDecsnResponse

// StkrtbdTrfDecsnParams is a generated OpenDART API schema type.
type StkrtbdTrfDecsnParams = opendartschema.StkrtbdTrfDecsnParams

// CmpMgDecsnItem is a generated OpenDART API schema type.
type CmpMgDecsnItem = opendartschema.CmpMgDecsnItem

// CmpMgDecsnResponse is a generated OpenDART API schema type.
type CmpMgDecsnResponse = opendartschema.CmpMgDecsnResponse

// CmpMgDecsnParams is a generated OpenDART API schema type.
type CmpMgDecsnParams = opendartschema.CmpMgDecsnParams

// CmpDvDecsnItem is a generated OpenDART API schema type.
type CmpDvDecsnItem = opendartschema.CmpDvDecsnItem

// CmpDvDecsnResponse is a generated OpenDART API schema type.
type CmpDvDecsnResponse = opendartschema.CmpDvDecsnResponse

// CmpDvDecsnParams is a generated OpenDART API schema type.
type CmpDvDecsnParams = opendartschema.CmpDvDecsnParams

// CmpDvmgDecsnItem is a generated OpenDART API schema type.
type CmpDvmgDecsnItem = opendartschema.CmpDvmgDecsnItem

// CmpDvmgDecsnResponse is a generated OpenDART API schema type.
type CmpDvmgDecsnResponse = opendartschema.CmpDvmgDecsnResponse

// CmpDvmgDecsnParams is a generated OpenDART API schema type.
type CmpDvmgDecsnParams = opendartschema.CmpDvmgDecsnParams

// StkExtrDecsnItem is a generated OpenDART API schema type.
type StkExtrDecsnItem = opendartschema.StkExtrDecsnItem

// StkExtrDecsnResponse is a generated OpenDART API schema type.
type StkExtrDecsnResponse = opendartschema.StkExtrDecsnResponse

// StkExtrDecsnParams is a generated OpenDART API schema type.
type StkExtrDecsnParams = opendartschema.StkExtrDecsnParams

// EstkRsGroup1 is a generated OpenDART API schema type.
type EstkRsGroup1 = opendartschema.EstkRsGroup1

// EstkRsGroup1Item is a generated OpenDART API schema type.
type EstkRsGroup1Item = opendartschema.EstkRsGroup1Item

// EstkRsGroup2 is a generated OpenDART API schema type.
type EstkRsGroup2 = opendartschema.EstkRsGroup2

// EstkRsGroup2Item is a generated OpenDART API schema type.
type EstkRsGroup2Item = opendartschema.EstkRsGroup2Item

// EstkRsGroup3 is a generated OpenDART API schema type.
type EstkRsGroup3 = opendartschema.EstkRsGroup3

// EstkRsGroup3Item is a generated OpenDART API schema type.
type EstkRsGroup3Item = opendartschema.EstkRsGroup3Item

// EstkRsGroup4 is a generated OpenDART API schema type.
type EstkRsGroup4 = opendartschema.EstkRsGroup4

// EstkRsGroup4Item is a generated OpenDART API schema type.
type EstkRsGroup4Item = opendartschema.EstkRsGroup4Item

// EstkRsGroup5 is a generated OpenDART API schema type.
type EstkRsGroup5 = opendartschema.EstkRsGroup5

// EstkRsGroup5Item is a generated OpenDART API schema type.
type EstkRsGroup5Item = opendartschema.EstkRsGroup5Item

// EstkRsGroup6 is a generated OpenDART API schema type.
type EstkRsGroup6 = opendartschema.EstkRsGroup6

// EstkRsGroup6Item is a generated OpenDART API schema type.
type EstkRsGroup6Item = opendartschema.EstkRsGroup6Item

// EstkRsResponse is a generated OpenDART API schema type.
type EstkRsResponse = opendartschema.EstkRsResponse

// EstkRsResponse_Group_Item is a generated OpenDART API schema type.
type EstkRsResponse_Group_Item = opendartschema.EstkRsResponse_Group_Item

// EstkRsParams is a generated OpenDART API schema type.
type EstkRsParams = opendartschema.EstkRsParams

// BdRsGroup1 is a generated OpenDART API schema type.
type BdRsGroup1 = opendartschema.BdRsGroup1

// BdRsGroup1Item is a generated OpenDART API schema type.
type BdRsGroup1Item = opendartschema.BdRsGroup1Item

// BdRsGroup2 is a generated OpenDART API schema type.
type BdRsGroup2 = opendartschema.BdRsGroup2

// BdRsGroup2Item is a generated OpenDART API schema type.
type BdRsGroup2Item = opendartschema.BdRsGroup2Item

// BdRsGroup3 is a generated OpenDART API schema type.
type BdRsGroup3 = opendartschema.BdRsGroup3

// BdRsGroup3Item is a generated OpenDART API schema type.
type BdRsGroup3Item = opendartschema.BdRsGroup3Item

// BdRsGroup4 is a generated OpenDART API schema type.
type BdRsGroup4 = opendartschema.BdRsGroup4

// BdRsGroup4Item is a generated OpenDART API schema type.
type BdRsGroup4Item = opendartschema.BdRsGroup4Item

// BdRsResponse is a generated OpenDART API schema type.
type BdRsResponse = opendartschema.BdRsResponse

// BdRsResponse_Group_Item is a generated OpenDART API schema type.
type BdRsResponse_Group_Item = opendartschema.BdRsResponse_Group_Item

// BdRsParams is a generated OpenDART API schema type.
type BdRsParams = opendartschema.BdRsParams

// StkdpRsGroup1 is a generated OpenDART API schema type.
type StkdpRsGroup1 = opendartschema.StkdpRsGroup1

// StkdpRsGroup1Item is a generated OpenDART API schema type.
type StkdpRsGroup1Item = opendartschema.StkdpRsGroup1Item

// StkdpRsGroup2 is a generated OpenDART API schema type.
type StkdpRsGroup2 = opendartschema.StkdpRsGroup2

// StkdpRsGroup2Item is a generated OpenDART API schema type.
type StkdpRsGroup2Item = opendartschema.StkdpRsGroup2Item

// StkdpRsGroup3 is a generated OpenDART API schema type.
type StkdpRsGroup3 = opendartschema.StkdpRsGroup3

// StkdpRsGroup3Item is a generated OpenDART API schema type.
type StkdpRsGroup3Item = opendartschema.StkdpRsGroup3Item

// StkdpRsGroup4 is a generated OpenDART API schema type.
type StkdpRsGroup4 = opendartschema.StkdpRsGroup4

// StkdpRsGroup4Item is a generated OpenDART API schema type.
type StkdpRsGroup4Item = opendartschema.StkdpRsGroup4Item

// StkdpRsGroup5 is a generated OpenDART API schema type.
type StkdpRsGroup5 = opendartschema.StkdpRsGroup5

// StkdpRsGroup5Item is a generated OpenDART API schema type.
type StkdpRsGroup5Item = opendartschema.StkdpRsGroup5Item

// StkdpRsResponse is a generated OpenDART API schema type.
type StkdpRsResponse = opendartschema.StkdpRsResponse

// StkdpRsResponse_Group_Item is a generated OpenDART API schema type.
type StkdpRsResponse_Group_Item = opendartschema.StkdpRsResponse_Group_Item

// StkdpRsParams is a generated OpenDART API schema type.
type StkdpRsParams = opendartschema.StkdpRsParams

// MgRsGroup1 is a generated OpenDART API schema type.
type MgRsGroup1 = opendartschema.MgRsGroup1

// MgRsGroup1Item is a generated OpenDART API schema type.
type MgRsGroup1Item = opendartschema.MgRsGroup1Item

// MgRsGroup2 is a generated OpenDART API schema type.
type MgRsGroup2 = opendartschema.MgRsGroup2

// MgRsGroup2Item is a generated OpenDART API schema type.
type MgRsGroup2Item = opendartschema.MgRsGroup2Item

// MgRsGroup3 is a generated OpenDART API schema type.
type MgRsGroup3 = opendartschema.MgRsGroup3

// MgRsGroup3Item is a generated OpenDART API schema type.
type MgRsGroup3Item = opendartschema.MgRsGroup3Item

// MgRsResponse is a generated OpenDART API schema type.
type MgRsResponse = opendartschema.MgRsResponse

// MgRsResponse_Group_Item is a generated OpenDART API schema type.
type MgRsResponse_Group_Item = opendartschema.MgRsResponse_Group_Item

// MgRsParams is a generated OpenDART API schema type.
type MgRsParams = opendartschema.MgRsParams

// ExtrRsGroup1 is a generated OpenDART API schema type.
type ExtrRsGroup1 = opendartschema.ExtrRsGroup1

// ExtrRsGroup1Item is a generated OpenDART API schema type.
type ExtrRsGroup1Item = opendartschema.ExtrRsGroup1Item

// ExtrRsGroup2 is a generated OpenDART API schema type.
type ExtrRsGroup2 = opendartschema.ExtrRsGroup2

// ExtrRsGroup2Item is a generated OpenDART API schema type.
type ExtrRsGroup2Item = opendartschema.ExtrRsGroup2Item

// ExtrRsGroup3 is a generated OpenDART API schema type.
type ExtrRsGroup3 = opendartschema.ExtrRsGroup3

// ExtrRsGroup3Item is a generated OpenDART API schema type.
type ExtrRsGroup3Item = opendartschema.ExtrRsGroup3Item

// ExtrRsResponse is a generated OpenDART API schema type.
type ExtrRsResponse = opendartschema.ExtrRsResponse

// ExtrRsResponse_Group_Item is a generated OpenDART API schema type.
type ExtrRsResponse_Group_Item = opendartschema.ExtrRsResponse_Group_Item

// ExtrRsParams is a generated OpenDART API schema type.
type ExtrRsParams = opendartschema.ExtrRsParams

// DvRsGroup1 is a generated OpenDART API schema type.
type DvRsGroup1 = opendartschema.DvRsGroup1

// DvRsGroup1Item is a generated OpenDART API schema type.
type DvRsGroup1Item = opendartschema.DvRsGroup1Item

// DvRsGroup2 is a generated OpenDART API schema type.
type DvRsGroup2 = opendartschema.DvRsGroup2

// DvRsGroup2Item is a generated OpenDART API schema type.
type DvRsGroup2Item = opendartschema.DvRsGroup2Item

// DvRsGroup3 is a generated OpenDART API schema type.
type DvRsGroup3 = opendartschema.DvRsGroup3

// DvRsGroup3Item is a generated OpenDART API schema type.
type DvRsGroup3Item = opendartschema.DvRsGroup3Item

// DvRsResponse is a generated OpenDART API schema type.
type DvRsResponse = opendartschema.DvRsResponse

// DvRsResponse_Group_Item is a generated OpenDART API schema type.
type DvRsResponse_Group_Item = opendartschema.DvRsResponse_Group_Item

// DvRsParams is a generated OpenDART API schema type.
type DvRsParams = opendartschema.DvRsParams

// FnlttSinglIndxItem is a generated OpenDART API schema type.
type FnlttSinglIndxItem = opendartschema.FnlttSinglIndxItem

// FnlttSinglIndxResponse is a generated OpenDART API schema type.
type FnlttSinglIndxResponse = opendartschema.FnlttSinglIndxResponse

// FnlttSinglIndxParams is a generated OpenDART API schema type.
type FnlttSinglIndxParams = opendartschema.FnlttSinglIndxParams

// FnlttCmpnyIndxItem is a generated OpenDART API schema type.
type FnlttCmpnyIndxItem = opendartschema.FnlttCmpnyIndxItem

// FnlttCmpnyIndxResponse is a generated OpenDART API schema type.
type FnlttCmpnyIndxResponse = opendartschema.FnlttCmpnyIndxResponse

// FnlttCmpnyIndxParams is a generated OpenDART API schema type.
type FnlttCmpnyIndxParams = opendartschema.FnlttCmpnyIndxParams

// HmvAuditIndvdlBySttusV2Group1 is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusV2Group1 = opendartschema.HmvAuditIndvdlBySttusV2Group1

// HmvAuditIndvdlBySttusV2Group1Item is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusV2Group1Item = opendartschema.HmvAuditIndvdlBySttusV2Group1Item

// HmvAuditIndvdlBySttusV2Response is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusV2Response = opendartschema.HmvAuditIndvdlBySttusV2Response

// HmvAuditIndvdlBySttusV2Response_Group_Item is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusV2Response_Group_Item = opendartschema.HmvAuditIndvdlBySttusV2Response_Group_Item

// HmvAuditIndvdlBySttusV2Params is a generated OpenDART API schema type.
type HmvAuditIndvdlBySttusV2Params = opendartschema.HmvAuditIndvdlBySttusV2Params

// IndvdlByPayV2Group1 is a generated OpenDART API schema type.
type IndvdlByPayV2Group1 = opendartschema.IndvdlByPayV2Group1

// IndvdlByPayV2Group1Item is a generated OpenDART API schema type.
type IndvdlByPayV2Group1Item = opendartschema.IndvdlByPayV2Group1Item

// IndvdlByPayV2Response is a generated OpenDART API schema type.
type IndvdlByPayV2Response = opendartschema.IndvdlByPayV2Response

// IndvdlByPayV2Response_Group_Item is a generated OpenDART API schema type.
type IndvdlByPayV2Response_Group_Item = opendartschema.IndvdlByPayV2Response_Group_Item

// IndvdlByPayV2Params is a generated OpenDART API schema type.
type IndvdlByPayV2Params = opendartschema.IndvdlByPayV2Params
