// Code generated by internal/generated/opendartapi/generate_split.py; DO NOT EDIT.

package opendart

import (
	"context"

	opendartapi "github.com/awuzag/opendart/internal/generated/opendartapi"
)

// List calls the generated OpenDART list API operation.
func (client *Client) List(ctx context.Context, params ListParams) (*ListResponse, error) {
	return opendartapi.List(ctx, client.apiCaller, params)
}

// CompanyRaw calls the generated OpenDART company API operation. The Raw suffix avoids a handwritten SDK method name collision.
func (client *Client) CompanyRaw(ctx context.Context, params CompanyParams) (*CompanyResponse, error) {
	return opendartapi.Company(ctx, client.apiCaller, params)
}

// DocumentRaw calls the generated OpenDART document API operation. The Raw suffix avoids a handwritten SDK method name collision.
func (client *Client) DocumentRaw(ctx context.Context, params DocumentParams) (*FileResponse, error) {
	result, err := opendartapi.Document(ctx, client.apiCaller, params)
	if err != nil {
		return nil, err
	}
	return &FileResponse{ContentType: result.ContentType, Body: result.Body}, nil
}

// CorpCode calls the generated OpenDART corpCode API operation.
func (client *Client) CorpCode(ctx context.Context) (*FileResponse, error) {
	result, err := opendartapi.CorpCode(ctx, client.apiCaller)
	if err != nil {
		return nil, err
	}
	return &FileResponse{ContentType: result.ContentType, Body: result.Body}, nil
}

// IrdsSttus calls the generated OpenDART irdsSttus API operation.
func (client *Client) IrdsSttus(ctx context.Context, params IrdsSttusParams) (*IrdsSttusResponse, error) {
	return opendartapi.IrdsSttus(ctx, client.apiCaller, params)
}

// AlotMatter calls the generated OpenDART alotMatter API operation.
func (client *Client) AlotMatter(ctx context.Context, params AlotMatterParams) (*AlotMatterResponse, error) {
	return opendartapi.AlotMatter(ctx, client.apiCaller, params)
}

// TesstkAcqsDspsSttus calls the generated OpenDART tesstkAcqsDspsSttus API operation.
func (client *Client) TesstkAcqsDspsSttus(ctx context.Context, params TesstkAcqsDspsSttusParams) (*TesstkAcqsDspsSttusResponse, error) {
	return opendartapi.TesstkAcqsDspsSttus(ctx, client.apiCaller, params)
}

// HyslrSttus calls the generated OpenDART hyslrSttus API operation.
func (client *Client) HyslrSttus(ctx context.Context, params HyslrSttusParams) (*HyslrSttusResponse, error) {
	return opendartapi.HyslrSttus(ctx, client.apiCaller, params)
}

// HyslrChgSttus calls the generated OpenDART hyslrChgSttus API operation.
func (client *Client) HyslrChgSttus(ctx context.Context, params HyslrChgSttusParams) (*HyslrChgSttusResponse, error) {
	return opendartapi.HyslrChgSttus(ctx, client.apiCaller, params)
}

// MrhlSttus calls the generated OpenDART mrhlSttus API operation.
func (client *Client) MrhlSttus(ctx context.Context, params MrhlSttusParams) (*MrhlSttusResponse, error) {
	return opendartapi.MrhlSttus(ctx, client.apiCaller, params)
}

// ExctvSttus calls the generated OpenDART exctvSttus API operation.
func (client *Client) ExctvSttus(ctx context.Context, params ExctvSttusParams) (*ExctvSttusResponse, error) {
	return opendartapi.ExctvSttus(ctx, client.apiCaller, params)
}

// EmpSttus calls the generated OpenDART empSttus API operation.
func (client *Client) EmpSttus(ctx context.Context, params EmpSttusParams) (*EmpSttusResponse, error) {
	return opendartapi.EmpSttus(ctx, client.apiCaller, params)
}

// HmvAuditIndvdlBySttus calls the generated OpenDART hmvAuditIndvdlBySttus API operation.
func (client *Client) HmvAuditIndvdlBySttus(ctx context.Context, params HmvAuditIndvdlBySttusParams) (*HmvAuditIndvdlBySttusResponse, error) {
	return opendartapi.HmvAuditIndvdlBySttus(ctx, client.apiCaller, params)
}

// HmvAuditAllSttus calls the generated OpenDART hmvAuditAllSttus API operation.
func (client *Client) HmvAuditAllSttus(ctx context.Context, params HmvAuditAllSttusParams) (*HmvAuditAllSttusResponse, error) {
	return opendartapi.HmvAuditAllSttus(ctx, client.apiCaller, params)
}

// IndvdlByPay calls the generated OpenDART indvdlByPay API operation.
func (client *Client) IndvdlByPay(ctx context.Context, params IndvdlByPayParams) (*IndvdlByPayResponse, error) {
	return opendartapi.IndvdlByPay(ctx, client.apiCaller, params)
}

// OtrCprInvstmntSttus calls the generated OpenDART otrCprInvstmntSttus API operation.
func (client *Client) OtrCprInvstmntSttus(ctx context.Context, params OtrCprInvstmntSttusParams) (*OtrCprInvstmntSttusResponse, error) {
	return opendartapi.OtrCprInvstmntSttus(ctx, client.apiCaller, params)
}

// StockTotqySttus calls the generated OpenDART stockTotqySttus API operation.
func (client *Client) StockTotqySttus(ctx context.Context, params StockTotqySttusParams) (*StockTotqySttusResponse, error) {
	return opendartapi.StockTotqySttus(ctx, client.apiCaller, params)
}

// DetScritsIsuAcmslt calls the generated OpenDART detScritsIsuAcmslt API operation.
func (client *Client) DetScritsIsuAcmslt(ctx context.Context, params DetScritsIsuAcmsltParams) (*DetScritsIsuAcmsltResponse, error) {
	return opendartapi.DetScritsIsuAcmslt(ctx, client.apiCaller, params)
}

// EntrprsBilScritsNrdmpBlce calls the generated OpenDART entrprsBilScritsNrdmpBlce API operation.
func (client *Client) EntrprsBilScritsNrdmpBlce(ctx context.Context, params EntrprsBilScritsNrdmpBlceParams) (*EntrprsBilScritsNrdmpBlceResponse, error) {
	return opendartapi.EntrprsBilScritsNrdmpBlce(ctx, client.apiCaller, params)
}

// SrtpdPsndbtNrdmpBlce calls the generated OpenDART srtpdPsndbtNrdmpBlce API operation.
func (client *Client) SrtpdPsndbtNrdmpBlce(ctx context.Context, params SrtpdPsndbtNrdmpBlceParams) (*SrtpdPsndbtNrdmpBlceResponse, error) {
	return opendartapi.SrtpdPsndbtNrdmpBlce(ctx, client.apiCaller, params)
}

// CprndNrdmpBlce calls the generated OpenDART cprndNrdmpBlce API operation.
func (client *Client) CprndNrdmpBlce(ctx context.Context, params CprndNrdmpBlceParams) (*CprndNrdmpBlceResponse, error) {
	return opendartapi.CprndNrdmpBlce(ctx, client.apiCaller, params)
}

// NewCaplScritsNrdmpBlce calls the generated OpenDART newCaplScritsNrdmpBlce API operation.
func (client *Client) NewCaplScritsNrdmpBlce(ctx context.Context, params NewCaplScritsNrdmpBlceParams) (*NewCaplScritsNrdmpBlceResponse, error) {
	return opendartapi.NewCaplScritsNrdmpBlce(ctx, client.apiCaller, params)
}

// CndlCaplScritsNrdmpBlce calls the generated OpenDART cndlCaplScritsNrdmpBlce API operation.
func (client *Client) CndlCaplScritsNrdmpBlce(ctx context.Context, params CndlCaplScritsNrdmpBlceParams) (*CndlCaplScritsNrdmpBlceResponse, error) {
	return opendartapi.CndlCaplScritsNrdmpBlce(ctx, client.apiCaller, params)
}

// AccnutAdtorNmNdAdtOpinion calls the generated OpenDART accnutAdtorNmNdAdtOpinion API operation.
func (client *Client) AccnutAdtorNmNdAdtOpinion(ctx context.Context, params AccnutAdtorNmNdAdtOpinionParams) (*AccnutAdtorNmNdAdtOpinionResponse, error) {
	return opendartapi.AccnutAdtorNmNdAdtOpinion(ctx, client.apiCaller, params)
}

// AdtServcCnclsSttus calls the generated OpenDART adtServcCnclsSttus API operation.
func (client *Client) AdtServcCnclsSttus(ctx context.Context, params AdtServcCnclsSttusParams) (*AdtServcCnclsSttusResponse, error) {
	return opendartapi.AdtServcCnclsSttus(ctx, client.apiCaller, params)
}

// AccnutAdtorNonAdtServcCnclsSttus calls the generated OpenDART accnutAdtorNonAdtServcCnclsSttus API operation.
func (client *Client) AccnutAdtorNonAdtServcCnclsSttus(ctx context.Context, params AccnutAdtorNonAdtServcCnclsSttusParams) (*AccnutAdtorNonAdtServcCnclsSttusResponse, error) {
	return opendartapi.AccnutAdtorNonAdtServcCnclsSttus(ctx, client.apiCaller, params)
}

// OutcmpnyDrctrNdChangeSttus calls the generated OpenDART outcmpnyDrctrNdChangeSttus API operation.
func (client *Client) OutcmpnyDrctrNdChangeSttus(ctx context.Context, params OutcmpnyDrctrNdChangeSttusParams) (*OutcmpnyDrctrNdChangeSttusResponse, error) {
	return opendartapi.OutcmpnyDrctrNdChangeSttus(ctx, client.apiCaller, params)
}

// UnrstExctvMendngSttus calls the generated OpenDART unrstExctvMendngSttus API operation.
func (client *Client) UnrstExctvMendngSttus(ctx context.Context, params UnrstExctvMendngSttusParams) (*UnrstExctvMendngSttusResponse, error) {
	return opendartapi.UnrstExctvMendngSttus(ctx, client.apiCaller, params)
}

// DrctrAdtAllMendngSttusGmtsckConfmAmount calls the generated OpenDART drctrAdtAllMendngSttusGmtsckConfmAmount API operation.
func (client *Client) DrctrAdtAllMendngSttusGmtsckConfmAmount(ctx context.Context, params DrctrAdtAllMendngSttusGmtsckConfmAmountParams) (*DrctrAdtAllMendngSttusGmtsckConfmAmountResponse, error) {
	return opendartapi.DrctrAdtAllMendngSttusGmtsckConfmAmount(ctx, client.apiCaller, params)
}

// DrctrAdtAllMendngSttusMendngPymntamtTyCl calls the generated OpenDART drctrAdtAllMendngSttusMendngPymntamtTyCl API operation.
func (client *Client) DrctrAdtAllMendngSttusMendngPymntamtTyCl(ctx context.Context, params DrctrAdtAllMendngSttusMendngPymntamtTyClParams) (*DrctrAdtAllMendngSttusMendngPymntamtTyClResponse, error) {
	return opendartapi.DrctrAdtAllMendngSttusMendngPymntamtTyCl(ctx, client.apiCaller, params)
}

// PssrpCptalUseDtls calls the generated OpenDART pssrpCptalUseDtls API operation.
func (client *Client) PssrpCptalUseDtls(ctx context.Context, params PssrpCptalUseDtlsParams) (*PssrpCptalUseDtlsResponse, error) {
	return opendartapi.PssrpCptalUseDtls(ctx, client.apiCaller, params)
}

// PrvsrpCptalUseDtls calls the generated OpenDART prvsrpCptalUseDtls API operation.
func (client *Client) PrvsrpCptalUseDtls(ctx context.Context, params PrvsrpCptalUseDtlsParams) (*PrvsrpCptalUseDtlsResponse, error) {
	return opendartapi.PrvsrpCptalUseDtls(ctx, client.apiCaller, params)
}

// HmvAuditIndvdlBySttusV2 calls the generated OpenDART hmvAuditIndvdlBySttusV2 API operation.
func (client *Client) HmvAuditIndvdlBySttusV2(ctx context.Context, params HmvAuditIndvdlBySttusV2Params) (*HmvAuditIndvdlBySttusV2Response, error) {
	return opendartapi.HmvAuditIndvdlBySttusV2(ctx, client.apiCaller, params)
}

// IndvdlByPayV2 calls the generated OpenDART indvdlByPayV2 API operation.
func (client *Client) IndvdlByPayV2(ctx context.Context, params IndvdlByPayV2Params) (*IndvdlByPayV2Response, error) {
	return opendartapi.IndvdlByPayV2(ctx, client.apiCaller, params)
}

// FnlttSinglAcnt calls the generated OpenDART fnlttSinglAcnt API operation.
func (client *Client) FnlttSinglAcnt(ctx context.Context, params FnlttSinglAcntParams) (*FnlttSinglAcntResponse, error) {
	return opendartapi.FnlttSinglAcnt(ctx, client.apiCaller, params)
}

// FnlttMultiAcnt calls the generated OpenDART fnlttMultiAcnt API operation.
func (client *Client) FnlttMultiAcnt(ctx context.Context, params FnlttMultiAcntParams) (*FnlttMultiAcntResponse, error) {
	return opendartapi.FnlttMultiAcnt(ctx, client.apiCaller, params)
}

// FnlttXbrl calls the generated OpenDART fnlttXbrl API operation.
func (client *Client) FnlttXbrl(ctx context.Context, params FnlttXbrlParams) (*FileResponse, error) {
	result, err := opendartapi.FnlttXbrl(ctx, client.apiCaller, params)
	if err != nil {
		return nil, err
	}
	return &FileResponse{ContentType: result.ContentType, Body: result.Body}, nil
}

// FnlttSinglAcntAll calls the generated OpenDART fnlttSinglAcntAll API operation.
func (client *Client) FnlttSinglAcntAll(ctx context.Context, params FnlttSinglAcntAllParams) (*FnlttSinglAcntAllResponse, error) {
	return opendartapi.FnlttSinglAcntAll(ctx, client.apiCaller, params)
}

// XbrlTaxonomy calls the generated OpenDART xbrlTaxonomy API operation.
func (client *Client) XbrlTaxonomy(ctx context.Context, params XbrlTaxonomyParams) (*XbrlTaxonomyResponse, error) {
	return opendartapi.XbrlTaxonomy(ctx, client.apiCaller, params)
}

// FnlttSinglIndx calls the generated OpenDART fnlttSinglIndx API operation.
func (client *Client) FnlttSinglIndx(ctx context.Context, params FnlttSinglIndxParams) (*FnlttSinglIndxResponse, error) {
	return opendartapi.FnlttSinglIndx(ctx, client.apiCaller, params)
}

// FnlttCmpnyIndx calls the generated OpenDART fnlttCmpnyIndx API operation.
func (client *Client) FnlttCmpnyIndx(ctx context.Context, params FnlttCmpnyIndxParams) (*FnlttCmpnyIndxResponse, error) {
	return opendartapi.FnlttCmpnyIndx(ctx, client.apiCaller, params)
}

// Majorstock calls the generated OpenDART majorstock API operation.
func (client *Client) Majorstock(ctx context.Context, params MajorstockParams) (*MajorstockResponse, error) {
	return opendartapi.Majorstock(ctx, client.apiCaller, params)
}

// Elestock calls the generated OpenDART elestock API operation.
func (client *Client) Elestock(ctx context.Context, params ElestockParams) (*ElestockResponse, error) {
	return opendartapi.Elestock(ctx, client.apiCaller, params)
}

// AstInhtrfEtcPtbkOpt calls the generated OpenDART astInhtrfEtcPtbkOpt API operation.
func (client *Client) AstInhtrfEtcPtbkOpt(ctx context.Context, params AstInhtrfEtcPtbkOptParams) (*AstInhtrfEtcPtbkOptResponse, error) {
	return opendartapi.AstInhtrfEtcPtbkOpt(ctx, client.apiCaller, params)
}

// DfOcr calls the generated OpenDART dfOcr API operation.
func (client *Client) DfOcr(ctx context.Context, params DfOcrParams) (*DfOcrResponse, error) {
	return opendartapi.DfOcr(ctx, client.apiCaller, params)
}

// BsnSp calls the generated OpenDART bsnSp API operation.
func (client *Client) BsnSp(ctx context.Context, params BsnSpParams) (*BsnSpResponse, error) {
	return opendartapi.BsnSp(ctx, client.apiCaller, params)
}

// CtrcvsBgrq calls the generated OpenDART ctrcvsBgrq API operation.
func (client *Client) CtrcvsBgrq(ctx context.Context, params CtrcvsBgrqParams) (*CtrcvsBgrqResponse, error) {
	return opendartapi.CtrcvsBgrq(ctx, client.apiCaller, params)
}

// DsRsOcr calls the generated OpenDART dsRsOcr API operation.
func (client *Client) DsRsOcr(ctx context.Context, params DsRsOcrParams) (*DsRsOcrResponse, error) {
	return opendartapi.DsRsOcr(ctx, client.apiCaller, params)
}

// PiicDecsn calls the generated OpenDART piicDecsn API operation.
func (client *Client) PiicDecsn(ctx context.Context, params PiicDecsnParams) (*PiicDecsnResponse, error) {
	return opendartapi.PiicDecsn(ctx, client.apiCaller, params)
}

// FricDecsn calls the generated OpenDART fricDecsn API operation.
func (client *Client) FricDecsn(ctx context.Context, params FricDecsnParams) (*FricDecsnResponse, error) {
	return opendartapi.FricDecsn(ctx, client.apiCaller, params)
}

// PifricDecsn calls the generated OpenDART pifricDecsn API operation.
func (client *Client) PifricDecsn(ctx context.Context, params PifricDecsnParams) (*PifricDecsnResponse, error) {
	return opendartapi.PifricDecsn(ctx, client.apiCaller, params)
}

// CrDecsn calls the generated OpenDART crDecsn API operation.
func (client *Client) CrDecsn(ctx context.Context, params CrDecsnParams) (*CrDecsnResponse, error) {
	return opendartapi.CrDecsn(ctx, client.apiCaller, params)
}

// BnkMngtPcbg calls the generated OpenDART bnkMngtPcbg API operation.
func (client *Client) BnkMngtPcbg(ctx context.Context, params BnkMngtPcbgParams) (*BnkMngtPcbgResponse, error) {
	return opendartapi.BnkMngtPcbg(ctx, client.apiCaller, params)
}

// LwstLg calls the generated OpenDART lwstLg API operation.
func (client *Client) LwstLg(ctx context.Context, params LwstLgParams) (*LwstLgResponse, error) {
	return opendartapi.LwstLg(ctx, client.apiCaller, params)
}

// OvLstDecsn calls the generated OpenDART ovLstDecsn API operation.
func (client *Client) OvLstDecsn(ctx context.Context, params OvLstDecsnParams) (*OvLstDecsnResponse, error) {
	return opendartapi.OvLstDecsn(ctx, client.apiCaller, params)
}

// OvDlstDecsn calls the generated OpenDART ovDlstDecsn API operation.
func (client *Client) OvDlstDecsn(ctx context.Context, params OvDlstDecsnParams) (*OvDlstDecsnResponse, error) {
	return opendartapi.OvDlstDecsn(ctx, client.apiCaller, params)
}

// OvLst calls the generated OpenDART ovLst API operation.
func (client *Client) OvLst(ctx context.Context, params OvLstParams) (*OvLstResponse, error) {
	return opendartapi.OvLst(ctx, client.apiCaller, params)
}

// OvDlst calls the generated OpenDART ovDlst API operation.
func (client *Client) OvDlst(ctx context.Context, params OvDlstParams) (*OvDlstResponse, error) {
	return opendartapi.OvDlst(ctx, client.apiCaller, params)
}

// CvbdIsDecsn calls the generated OpenDART cvbdIsDecsn API operation.
func (client *Client) CvbdIsDecsn(ctx context.Context, params CvbdIsDecsnParams) (*CvbdIsDecsnResponse, error) {
	return opendartapi.CvbdIsDecsn(ctx, client.apiCaller, params)
}

// BdwtIsDecsn calls the generated OpenDART bdwtIsDecsn API operation.
func (client *Client) BdwtIsDecsn(ctx context.Context, params BdwtIsDecsnParams) (*BdwtIsDecsnResponse, error) {
	return opendartapi.BdwtIsDecsn(ctx, client.apiCaller, params)
}

// ExbdIsDecsn calls the generated OpenDART exbdIsDecsn API operation.
func (client *Client) ExbdIsDecsn(ctx context.Context, params ExbdIsDecsnParams) (*ExbdIsDecsnResponse, error) {
	return opendartapi.ExbdIsDecsn(ctx, client.apiCaller, params)
}

// BnkMngtPcsp calls the generated OpenDART bnkMngtPcsp API operation.
func (client *Client) BnkMngtPcsp(ctx context.Context, params BnkMngtPcspParams) (*BnkMngtPcspResponse, error) {
	return opendartapi.BnkMngtPcsp(ctx, client.apiCaller, params)
}

// WdCocobdIsDecsn calls the generated OpenDART wdCocobdIsDecsn API operation.
func (client *Client) WdCocobdIsDecsn(ctx context.Context, params WdCocobdIsDecsnParams) (*WdCocobdIsDecsnResponse, error) {
	return opendartapi.WdCocobdIsDecsn(ctx, client.apiCaller, params)
}

// TsstkAqDecsn calls the generated OpenDART tsstkAqDecsn API operation.
func (client *Client) TsstkAqDecsn(ctx context.Context, params TsstkAqDecsnParams) (*TsstkAqDecsnResponse, error) {
	return opendartapi.TsstkAqDecsn(ctx, client.apiCaller, params)
}

// TsstkDpDecsn calls the generated OpenDART tsstkDpDecsn API operation.
func (client *Client) TsstkDpDecsn(ctx context.Context, params TsstkDpDecsnParams) (*TsstkDpDecsnResponse, error) {
	return opendartapi.TsstkDpDecsn(ctx, client.apiCaller, params)
}

// TsstkAqTrctrCnsDecsn calls the generated OpenDART tsstkAqTrctrCnsDecsn API operation.
func (client *Client) TsstkAqTrctrCnsDecsn(ctx context.Context, params TsstkAqTrctrCnsDecsnParams) (*TsstkAqTrctrCnsDecsnResponse, error) {
	return opendartapi.TsstkAqTrctrCnsDecsn(ctx, client.apiCaller, params)
}

// TsstkAqTrctrCcDecsn calls the generated OpenDART tsstkAqTrctrCcDecsn API operation.
func (client *Client) TsstkAqTrctrCcDecsn(ctx context.Context, params TsstkAqTrctrCcDecsnParams) (*TsstkAqTrctrCcDecsnResponse, error) {
	return opendartapi.TsstkAqTrctrCcDecsn(ctx, client.apiCaller, params)
}

// BsnInhDecsn calls the generated OpenDART bsnInhDecsn API operation.
func (client *Client) BsnInhDecsn(ctx context.Context, params BsnInhDecsnParams) (*BsnInhDecsnResponse, error) {
	return opendartapi.BsnInhDecsn(ctx, client.apiCaller, params)
}

// BsnTrfDecsn calls the generated OpenDART bsnTrfDecsn API operation.
func (client *Client) BsnTrfDecsn(ctx context.Context, params BsnTrfDecsnParams) (*BsnTrfDecsnResponse, error) {
	return opendartapi.BsnTrfDecsn(ctx, client.apiCaller, params)
}

// TgastInhDecsn calls the generated OpenDART tgastInhDecsn API operation.
func (client *Client) TgastInhDecsn(ctx context.Context, params TgastInhDecsnParams) (*TgastInhDecsnResponse, error) {
	return opendartapi.TgastInhDecsn(ctx, client.apiCaller, params)
}

// TgastTrfDecsn calls the generated OpenDART tgastTrfDecsn API operation.
func (client *Client) TgastTrfDecsn(ctx context.Context, params TgastTrfDecsnParams) (*TgastTrfDecsnResponse, error) {
	return opendartapi.TgastTrfDecsn(ctx, client.apiCaller, params)
}

// OtcprStkInvscrInhDecsn calls the generated OpenDART otcprStkInvscrInhDecsn API operation.
func (client *Client) OtcprStkInvscrInhDecsn(ctx context.Context, params OtcprStkInvscrInhDecsnParams) (*OtcprStkInvscrInhDecsnResponse, error) {
	return opendartapi.OtcprStkInvscrInhDecsn(ctx, client.apiCaller, params)
}

// OtcprStkInvscrTrfDecsn calls the generated OpenDART otcprStkInvscrTrfDecsn API operation.
func (client *Client) OtcprStkInvscrTrfDecsn(ctx context.Context, params OtcprStkInvscrTrfDecsnParams) (*OtcprStkInvscrTrfDecsnResponse, error) {
	return opendartapi.OtcprStkInvscrTrfDecsn(ctx, client.apiCaller, params)
}

// StkrtbdInhDecsn calls the generated OpenDART stkrtbdInhDecsn API operation.
func (client *Client) StkrtbdInhDecsn(ctx context.Context, params StkrtbdInhDecsnParams) (*StkrtbdInhDecsnResponse, error) {
	return opendartapi.StkrtbdInhDecsn(ctx, client.apiCaller, params)
}

// StkrtbdTrfDecsn calls the generated OpenDART stkrtbdTrfDecsn API operation.
func (client *Client) StkrtbdTrfDecsn(ctx context.Context, params StkrtbdTrfDecsnParams) (*StkrtbdTrfDecsnResponse, error) {
	return opendartapi.StkrtbdTrfDecsn(ctx, client.apiCaller, params)
}

// CmpMgDecsn calls the generated OpenDART cmpMgDecsn API operation.
func (client *Client) CmpMgDecsn(ctx context.Context, params CmpMgDecsnParams) (*CmpMgDecsnResponse, error) {
	return opendartapi.CmpMgDecsn(ctx, client.apiCaller, params)
}

// CmpDvDecsn calls the generated OpenDART cmpDvDecsn API operation.
func (client *Client) CmpDvDecsn(ctx context.Context, params CmpDvDecsnParams) (*CmpDvDecsnResponse, error) {
	return opendartapi.CmpDvDecsn(ctx, client.apiCaller, params)
}

// CmpDvmgDecsn calls the generated OpenDART cmpDvmgDecsn API operation.
func (client *Client) CmpDvmgDecsn(ctx context.Context, params CmpDvmgDecsnParams) (*CmpDvmgDecsnResponse, error) {
	return opendartapi.CmpDvmgDecsn(ctx, client.apiCaller, params)
}

// StkExtrDecsn calls the generated OpenDART stkExtrDecsn API operation.
func (client *Client) StkExtrDecsn(ctx context.Context, params StkExtrDecsnParams) (*StkExtrDecsnResponse, error) {
	return opendartapi.StkExtrDecsn(ctx, client.apiCaller, params)
}

// EstkRs calls the generated OpenDART estkRs API operation.
func (client *Client) EstkRs(ctx context.Context, params EstkRsParams) (*EstkRsResponse, error) {
	return opendartapi.EstkRs(ctx, client.apiCaller, params)
}

// BdRs calls the generated OpenDART bdRs API operation.
func (client *Client) BdRs(ctx context.Context, params BdRsParams) (*BdRsResponse, error) {
	return opendartapi.BdRs(ctx, client.apiCaller, params)
}

// StkdpRs calls the generated OpenDART stkdpRs API operation.
func (client *Client) StkdpRs(ctx context.Context, params StkdpRsParams) (*StkdpRsResponse, error) {
	return opendartapi.StkdpRs(ctx, client.apiCaller, params)
}

// MgRs calls the generated OpenDART mgRs API operation.
func (client *Client) MgRs(ctx context.Context, params MgRsParams) (*MgRsResponse, error) {
	return opendartapi.MgRs(ctx, client.apiCaller, params)
}

// ExtrRs calls the generated OpenDART extrRs API operation.
func (client *Client) ExtrRs(ctx context.Context, params ExtrRsParams) (*ExtrRsResponse, error) {
	return opendartapi.ExtrRs(ctx, client.apiCaller, params)
}

// DvRs calls the generated OpenDART dvRs API operation.
func (client *Client) DvRs(ctx context.Context, params DvRsParams) (*DvRsResponse, error) {
	return opendartapi.DvRs(ctx, client.apiCaller, params)
}
