package cli

var apiCatalog = []apiSpec{
	{
		Group:    "disclosure",
		Command:  "list",
		APIID:    "2019001",
		Name:     "공시검색",
		Endpoint: "/api/list.json",
		Params: []paramSpec{
			{Name: "corp_code", Description: "고유번호", Required: false},
			{Name: "bgn_de", Description: "시작일", Required: false},
			{Name: "end_de", Description: "종료일", Required: false},
			{Name: "last_reprt_at", Description: "최종보고서 검색여부", Required: false},
			{Name: "pblntf_ty", Description: "공시유형", Required: false},
			{Name: "pblntf_detail_ty", Description: "공시상세유형", Required: false},
			{Name: "corp_cls", Description: "법인구분", Required: false},
			{Name: "sort", Description: "정렬", Required: false},
			{Name: "sort_mth", Description: "정렬방법", Required: false},
			{Name: "page_no", Description: "페이지 번호", Required: false},
			{Name: "page_count", Description: "페이지 별 건수", Required: false},
		},
	},
	{
		Group:    "disclosure",
		Command:  "company",
		APIID:    "2019002",
		Name:     "기업개황",
		Endpoint: "/api/company.json",
		Params: []paramSpec{
			{Name: "corp_code", Description: "고유번호", Required: true},
		},
	},
	{
		Group:    "disclosure",
		Command:  "document",
		APIID:    "2019003",
		Name:     "공시서류원본파일",
		Endpoint: "/api/document.xml",
		Params: []paramSpec{
			{Name: "rcept_no", Description: "접수번호", Required: true},
		},
	},
	{
		Group:    "disclosure",
		Command:  "corp-code",
		APIID:    "2019018",
		Name:     "고유번호",
		Endpoint: "/api/corpCode.xml",
	},
	{
		Group:    "company",
		Command:  "irds-sttus",
		APIID:    "2019004",
		Name:     "증자(감자) 현황",
		Endpoint: "/api/irdsSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "alot-matter",
		APIID:    "2019005",
		Name:     "배당에 관한 사항",
		Endpoint: "/api/alotMatter.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "tesstk-acqs-dsps-sttus",
		APIID:    "2019006",
		Name:     "자기주식 취득 및 처분 현황",
		Endpoint: "/api/tesstkAcqsDspsSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "hyslr-sttus",
		APIID:    "2019007",
		Name:     "최대주주 현황",
		Endpoint: "/api/hyslrSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "hyslr-chg-sttus",
		APIID:    "2019008",
		Name:     "최대주주 변동현황",
		Endpoint: "/api/hyslrChgSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "mrhl-sttus",
		APIID:    "2019009",
		Name:     "소액주주 현황",
		Endpoint: "/api/mrhlSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "exctv-sttus",
		APIID:    "2019010",
		Name:     "임원 현황",
		Endpoint: "/api/exctvSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "emp-sttus",
		APIID:    "2019011",
		Name:     "직원 현황",
		Endpoint: "/api/empSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "hmv-audit-indvdl-by-sttus",
		APIID:    "2019012",
		Name:     "이사·감사의 개인별 보수현황(5억원 이상)",
		Endpoint: "/api/hmvAuditIndvdlBySttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "hmv-audit-all-sttus",
		APIID:    "2019013",
		Name:     "이사·감사 전체의 보수현황(보수지급금액 - 이사·감사 전체)",
		Endpoint: "/api/hmvAuditAllSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "indvdl-by-pay",
		APIID:    "2019014",
		Name:     "개인별 보수지급 금액(5억이상 상위5인)",
		Endpoint: "/api/indvdlByPay.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "otr-cpr-invstmnt-sttus",
		APIID:    "2019015",
		Name:     "타법인 출자현황",
		Endpoint: "/api/otrCprInvstmntSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "stock-totqy-sttus",
		APIID:    "2020002",
		Name:     "주식의 총수 현황",
		Endpoint: "/api/stockTotqySttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "det-scrits-isu-acmslt",
		APIID:    "2020003",
		Name:     "채무증권 발행실적",
		Endpoint: "/api/detScritsIsuAcmslt.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "entrprs-bil-scrits-nrdmp-blce",
		APIID:    "2020004",
		Name:     "기업어음증권 미상환 잔액",
		Endpoint: "/api/entrprsBilScritsNrdmpBlce.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "srtpd-psndbt-nrdmp-blce",
		APIID:    "2020005",
		Name:     "단기사채 미상환 잔액",
		Endpoint: "/api/srtpdPsndbtNrdmpBlce.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "cprnd-nrdmp-blce",
		APIID:    "2020006",
		Name:     "회사채 미상환 잔액",
		Endpoint: "/api/cprndNrdmpBlce.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "new-capl-scrits-nrdmp-blce",
		APIID:    "2020007",
		Name:     "신종자본증권 미상환 잔액",
		Endpoint: "/api/newCaplScritsNrdmpBlce.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "cndl-capl-scrits-nrdmp-blce",
		APIID:    "2020008",
		Name:     "조건부 자본증권 미상환 잔액",
		Endpoint: "/api/cndlCaplScritsNrdmpBlce.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "accnut-adtor-nm-nd-adt-opinion",
		APIID:    "2020009",
		Name:     "회계감사인의 명칭 및 감사의견",
		Endpoint: "/api/accnutAdtorNmNdAdtOpinion.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "adt-servc-cncls-sttus",
		APIID:    "2020010",
		Name:     "감사용역체결현황",
		Endpoint: "/api/adtServcCnclsSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "accnut-adtor-non-adt-servc-cncls-sttus",
		APIID:    "2020011",
		Name:     "회계감사인과의 비감사용역 계약체결 현황",
		Endpoint: "/api/accnutAdtorNonAdtServcCnclsSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "outcmpny-drctr-nd-change-sttus",
		APIID:    "2020012",
		Name:     "사외이사 및 그 변동현황",
		Endpoint: "/api/outcmpnyDrctrNdChangeSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "unrst-exctv-mendng-sttus",
		APIID:    "2020013",
		Name:     "미등기임원 보수현황",
		Endpoint: "/api/unrstExctvMendngSttus.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "drctr-adt-all-mendng-sttus-gmtsck-confm-amount",
		APIID:    "2020014",
		Name:     "이사·감사 전체의 보수현황(주주총회 승인금액)",
		Endpoint: "/api/drctrAdtAllMendngSttusGmtsckConfmAmount.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "drctr-adt-all-mendng-sttus-mendng-pymntamt-ty-cl",
		APIID:    "2020015",
		Name:     "이사·감사 전체의 보수현황(보수지급금액 - 유형별)",
		Endpoint: "/api/drctrAdtAllMendngSttusMendngPymntamtTyCl.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "pssrp-cptal-use-dtls",
		APIID:    "2020016",
		Name:     "공모자금의 사용내역",
		Endpoint: "/api/pssrpCptalUseDtls.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "company",
		Command:  "prvsrp-cptal-use-dtls",
		APIID:    "2020017",
		Name:     "사모자금의 사용내역",
		Endpoint: "/api/prvsrpCptalUseDtls.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "financial",
		Command:  "single-account",
		APIID:    "2019016",
		Name:     "단일회사 주요계정",
		Endpoint: "/api/fnlttSinglAcnt.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "financial",
		Command:  "multi-account",
		APIID:    "2019017",
		Name:     "다중회사 주요계정",
		Endpoint: "/api/fnlttMultiAcnt.json",
		Params:   periodicReportParams(),
	},
	{
		Group:    "financial",
		Command:  "xbrl",
		APIID:    "2019019",
		Name:     "재무제표 원본파일(XBRL)",
		Endpoint: "/api/fnlttXbrl.xml",
		Params: []paramSpec{
			{Name: "rcept_no", Description: "접수번호", Required: true},
			{Name: "reprt_code", Description: "보고서 코드", Required: true},
		},
	},
	{
		Group:    "financial",
		Command:  "single-account-all",
		APIID:    "2019020",
		Name:     "단일회사 전체 재무제표",
		Endpoint: "/api/fnlttSinglAcntAll.json",
		Params: append(periodicReportParams(), paramSpec{
			Name:        "fs_div",
			Description: "개별/연결구분",
			Required:    true,
		}),
	},
	{
		Group:    "financial",
		Command:  "xbrl-taxonomy",
		APIID:    "2020001",
		Name:     "XBRL택사노미재무제표양식",
		Endpoint: "/api/xbrlTaxonomy.json",
		Params: []paramSpec{
			{Name: "sj_div", Description: "재무제표구분", Required: true},
		},
	},
	{
		Group:    "financial",
		Command:  "single-index",
		APIID:    "2022001",
		Name:     "단일회사 주요 재무지표",
		Endpoint: "/api/fnlttSinglIndx.json",
		Params: append(periodicReportParams(), paramSpec{
			Name:        "idx_cl_code",
			Description: "지표분류코드",
			Required:    true,
		}),
	},
	{
		Group:    "financial",
		Command:  "company-index",
		APIID:    "2022002",
		Name:     "다중회사 주요 재무지표",
		Endpoint: "/api/fnlttCmpnyIndx.json",
		Params: append(periodicReportParams(), paramSpec{
			Name:        "idx_cl_code",
			Description: "지표분류코드",
			Required:    true,
		}),
	},
	{
		Group:    "ownership",
		Command:  "major-stock",
		APIID:    "2019021",
		Name:     "대량보유 상황보고",
		Endpoint: "/api/majorstock.json",
		Params: []paramSpec{
			{Name: "corp_code", Description: "고유번호", Required: true},
		},
	},
	{
		Group:    "ownership",
		Command:  "executive-stock",
		APIID:    "2019022",
		Name:     "임원ㆍ주요주주 소유보고",
		Endpoint: "/api/elestock.json",
		Params: []paramSpec{
			{Name: "corp_code", Description: "고유번호", Required: true},
		},
	},
	{
		Group:    "material",
		Command:  "ast-inhtrf-etc-ptbk-opt",
		APIID:    "2020018",
		Name:     "자산양수도(기타), 풋백옵션",
		Endpoint: "/api/astInhtrfEtcPtbkOpt.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "df-ocr",
		APIID:    "2020019",
		Name:     "부도발생",
		Endpoint: "/api/dfOcr.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "bsn-sp",
		APIID:    "2020020",
		Name:     "영업정지",
		Endpoint: "/api/bsnSp.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "ctrcvs-bgrq",
		APIID:    "2020021",
		Name:     "회생절차 개시신청",
		Endpoint: "/api/ctrcvsBgrq.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "ds-rs-ocr",
		APIID:    "2020022",
		Name:     "해산사유 발생",
		Endpoint: "/api/dsRsOcr.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "piic-decsn",
		APIID:    "2020023",
		Name:     "유상증자 결정",
		Endpoint: "/api/piicDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "fric-decsn",
		APIID:    "2020024",
		Name:     "무상증자 결정",
		Endpoint: "/api/fricDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "pifric-decsn",
		APIID:    "2020025",
		Name:     "유무상증자 결정",
		Endpoint: "/api/pifricDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "cr-decsn",
		APIID:    "2020026",
		Name:     "감자 결정",
		Endpoint: "/api/crDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "bnk-mngt-pcbg",
		APIID:    "2020027",
		Name:     "채권은행 등의 관리절차 개시",
		Endpoint: "/api/bnkMngtPcbg.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "lwst-lg",
		APIID:    "2020028",
		Name:     "소송 등의 제기",
		Endpoint: "/api/lwstLg.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "ov-lst-decsn",
		APIID:    "2020029",
		Name:     "해외 증권시장 주권등 상장 결정",
		Endpoint: "/api/ovLstDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "ov-dlst-decsn",
		APIID:    "2020030",
		Name:     "해외 증권시장 주권등 상장폐지 결정",
		Endpoint: "/api/ovDlstDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "ov-lst",
		APIID:    "2020031",
		Name:     "해외 증권시장 주권등 상장",
		Endpoint: "/api/ovLst.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "ov-dlst",
		APIID:    "2020032",
		Name:     "해외 증권시장 주권등 상장폐지",
		Endpoint: "/api/ovDlst.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "cvbd-is-decsn",
		APIID:    "2020033",
		Name:     "전환사채권 발행결정",
		Endpoint: "/api/cvbdIsDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "bdwt-is-decsn",
		APIID:    "2020034",
		Name:     "신주인수권부사채권 발행결정",
		Endpoint: "/api/bdwtIsDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "exbd-is-decsn",
		APIID:    "2020035",
		Name:     "교환사채권 발행결정",
		Endpoint: "/api/exbdIsDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "bnk-mngt-pcsp",
		APIID:    "2020036",
		Name:     "채권은행 등의 관리절차 중단",
		Endpoint: "/api/bnkMngtPcsp.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "wd-cocobd-is-decsn",
		APIID:    "2020037",
		Name:     "상각형 조건부자본증권 발행결정",
		Endpoint: "/api/wdCocobdIsDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "tsstk-aq-decsn",
		APIID:    "2020038",
		Name:     "자기주식 취득 결정",
		Endpoint: "/api/tsstkAqDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "tsstk-dp-decsn",
		APIID:    "2020039",
		Name:     "자기주식 처분 결정",
		Endpoint: "/api/tsstkDpDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "tsstk-aq-trctr-cns-decsn",
		APIID:    "2020040",
		Name:     "자기주식취득 신탁계약 체결 결정",
		Endpoint: "/api/tsstkAqTrctrCnsDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "tsstk-aq-trctr-cc-decsn",
		APIID:    "2020041",
		Name:     "자기주식취득 신탁계약 해지 결정",
		Endpoint: "/api/tsstkAqTrctrCcDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "bsn-inh-decsn",
		APIID:    "2020042",
		Name:     "영업양수 결정",
		Endpoint: "/api/bsnInhDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "bsn-trf-decsn",
		APIID:    "2020043",
		Name:     "영업양도 결정",
		Endpoint: "/api/bsnTrfDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "tgast-inh-decsn",
		APIID:    "2020044",
		Name:     "유형자산 양수 결정",
		Endpoint: "/api/tgastInhDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "tgast-trf-decsn",
		APIID:    "2020045",
		Name:     "유형자산 양도 결정",
		Endpoint: "/api/tgastTrfDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "otcpr-stk-invscr-inh-decsn",
		APIID:    "2020046",
		Name:     "타법인 주식 및 출자증권 양수결정",
		Endpoint: "/api/otcprStkInvscrInhDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "otcpr-stk-invscr-trf-decsn",
		APIID:    "2020047",
		Name:     "타법인 주식 및 출자증권 양도결정",
		Endpoint: "/api/otcprStkInvscrTrfDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "stkrtbd-inh-decsn",
		APIID:    "2020048",
		Name:     "주권 관련 사채권 양수 결정",
		Endpoint: "/api/stkrtbdInhDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "stkrtbd-trf-decsn",
		APIID:    "2020049",
		Name:     "주권 관련 사채권 양도 결정",
		Endpoint: "/api/stkrtbdTrfDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "cmp-mg-decsn",
		APIID:    "2020050",
		Name:     "회사합병 결정",
		Endpoint: "/api/cmpMgDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "cmp-dv-decsn",
		APIID:    "2020051",
		Name:     "회사분할 결정",
		Endpoint: "/api/cmpDvDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "cmp-dvmg-decsn",
		APIID:    "2020052",
		Name:     "회사분할합병 결정",
		Endpoint: "/api/cmpDvmgDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "material",
		Command:  "stk-extr-decsn",
		APIID:    "2020053",
		Name:     "주식교환·이전 결정",
		Endpoint: "/api/stkExtrDecsn.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "registration",
		Command:  "equity",
		APIID:    "2020054",
		Name:     "지분증권",
		Endpoint: "/api/estkRs.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "registration",
		Command:  "debt",
		APIID:    "2020055",
		Name:     "채무증권",
		Endpoint: "/api/bdRs.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "registration",
		Command:  "depositary-receipt",
		APIID:    "2020056",
		Name:     "증권예탁증권",
		Endpoint: "/api/stkdpRs.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "registration",
		Command:  "merger",
		APIID:    "2020057",
		Name:     "합병",
		Endpoint: "/api/mgRs.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "registration",
		Command:  "share-exchange-transfer",
		APIID:    "2020058",
		Name:     "주식의포괄적교환·이전",
		Endpoint: "/api/extrRs.json",
		Params:   materialReportParams(),
	},
	{
		Group:    "registration",
		Command:  "division",
		APIID:    "2020059",
		Name:     "분할",
		Endpoint: "/api/dvRs.json",
		Params:   materialReportParams(),
	},
}

func periodicReportParams() []paramSpec {
	return []paramSpec{
		{Name: "corp_code", Description: "고유번호", Required: true},
		{Name: "bsns_year", Description: "사업연도", Required: true},
		{Name: "reprt_code", Description: "보고서 코드", Required: true},
	}
}

func materialReportParams() []paramSpec {
	return []paramSpec{
		{Name: "corp_code", Description: "고유번호", Required: true},
		{Name: "bgn_de", Description: "시작일(최초접수일)", Required: true},
		{Name: "end_de", Description: "종료일(최초접수일)", Required: true},
	}
}
